version: '3.1'
services:
  mrs-api:
    container_name: medical-result-api
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mrs-postgres:5432/mrs
    ports:
      - "8080:8080"
    depends_on:
      - mrs-postgres
  mrs-postgres:
    container_name: medical-result-db
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
      - POSTGRES_USER="${DB_USERNAME}"
      - POSTGRES_DB=mrs
    ports:
      - "5432:5432"
