jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mrs
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
